tap 'homebrew/dupes'

brew 'apg'
brew 'jsonpp'
brew 'nkf'
brew 'rsync'
brew 'source-highlight'
brew 'git'
brew 'phantomjs'
brew 'ssh-copy-id'
brew 'wget'
brew 'direnv'
brew 'pow'
brew 'zsh'
brew 'graphviz'
brew 'mysql'

brew 'caskroom/cask/brew-cask'

cask 'alfred'
cask 'bettertouchtool'
cask 'dash'

tap 'caskroom/homebrew-versions'
cask 'firefox-ja'

cask 'go2shell'
cask 'growlnotify'
cask 'iterm2'
cask 'parallels-desktop'
cask 'the-unarchiver'
cask 'slack'
cask 'rubymine'
